services:
  tcpapi:
    build: ./Server
    ports:
      - "9000:9000"
      - "5000:5000"
    environment:
      ConnectionStrings__PostgreSQL: "Host=postgres;Port=5432;Database=clamshell;Username=postgres;Password=yourpassword"
      ASPNETCORE_URLS: "http://+:5000"
      XCHACHA20POLY1305_KEY: ${XCHACHA20POLY1305_KEY}
      XCHACHA20POLY1305_NONCE: ${XCHACHA20POLY1305_NONCE}
      TCP_HOST: "0.0.0.0"
      TCP_PORT: "9000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: clamshell
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  node:
    build: ./Node
    environment:
      XCHACHA20POLY1305_KEY: ${XCHACHA20POLY1305_KEY}
      XCHACHA20POLY1305_NONCE: ${XCHACHA20POLY1305_NONCE}
      TCP_HOST: tcpapi
      TCP_PORT: "9000"
    restart: unless-stopped
    depends_on:
      - tcpapi

  website:
    build: ./website
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  postgres_data:
