CREATE TABLE messages (
    id SERIAL PRIMARY KEY,
    content TEXT,
    receivedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    signed BOOLEAN DEFAULT FALSE,
    validated BOOLEAN DEFAULT FALSE,
    pgn TEXT
);